modLoader = "kotlinforforge"
loaderVersion = "[5.11,)"
license = "All Rights Reserved"

[[mods]]
	modId = "create_ore_deposits"
	version = "0.1.0-alpha"
	displayName = "Create Ore Deposits"
	authors = "MCArctic, Mavity the Madity, Orion"
	description = ''''''

[[dependencies."create_ore_deposits"]]
	modId = "neoforge"
	type = "required"
	versionRange = "[21,)"
	ordering = "NONE"
	side = "BOTH"

[[dependencies."create_ore_deposits"]]
	modId = "minecraft"
	mandatory = true
	versionRange = "[1.21.1,1.22)"
	ordering = "NONE"
	side = "BOTH"

[[dependencies."create_ore_deposits"]]
	modId = "create"
	mandatory = true
	versionRange = "[6.0.0,)"
	ordering = "NONE"
	side = "BOTH"

[[dependencies."create_ore_deposits"]]
	modId = "kotlinforforge"
	mandatory = true
	type = "required"
	versionRange = "[5.11.0,)"
	ordering = "NONE"
	side = "BOTH"